# Generated by Django 5.2.8 on 2025-12-03 02:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instituicao', models.CharField(max_length=150, verbose_name='Nome da Instituição')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logotipo da Clínica')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('endereco_fisico', models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço Físico')),
                ('endereco_eletronico', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email Institucional')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Instituições',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_paciente', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID Único do Paciente')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('sintomas', models.TextField(blank=True, null=True)),
                ('possivel_diagnostico', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagemExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caminho_arquivo', models.FileField(upload_to='imagens_reais/', verbose_name='Arquivo da Imagem Real')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('descricao_opcional', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_imagem', models.CharField(default='Exame Real', max_length=50)),
                ('usuario_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que fez o upload')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.instituicao', verbose_name='Instituição')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.paciente', verbose_name='Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='AnaliseImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_hora_conclusao', models.DateTimeField(blank=True, null=True)),
                ('resultado_classificacao', models.CharField(choices=[('Maligno', 'Maligno'), ('Benigno', 'Benigno'), ('Cisto', 'Cisto'), ('Saudavel', 'Saudável')], max_length=10)),
                ('score_confianca', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('modelo_versao', models.CharField(max_length=50)),
                ('modelo_checksum', models.CharField(max_length=100)),
                ('hash_imagem', models.CharField(max_length=100)),
                ('usuario_solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Solicitante')),
                ('imagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nucleo.imagemexame', verbose_name='Imagem Analisada')),
            ],
            options={
                'verbose_name_plural': 'Análises de Imagem',
            },
        ),
        migrations.CreateModel(
            name='Laudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_emissao', models.DateTimeField(auto_now_add=True)),
                ('texto_laudo_completo', models.TextField()),
                ('caminho_pdf', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmou_concordancia', models.BooleanField(verbose_name='Confirma Concordância com IA')),
                ('ip_emissao', models.CharField(max_length=45, verbose_name='IP de Emissão')),
                ('laudo_finalizado', models.BooleanField(default=False, verbose_name='Finalizado/Bloqueado')),
                ('codigo_verificacao', models.CharField(max_length=50, unique=True)),
                ('analise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nucleo.analiseimagem', verbose_name='Análise de Origem')),
            ],
        ),
        migrations.CreateModel(
            name='LaudoImpressao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_impressao', models.DateTimeField(auto_now_add=True)),
                ('ip_origem', models.CharField(max_length=45)),
                ('local_impressao', models.CharField(blank=True, max_length=100, null=True)),
                ('laudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.laudo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('acao', models.CharField(choices=[('LOGIN_SUCESSO', 'Login Bem-Sucedido'), ('LOGIN_FALHA', 'Tentativa de Login Falha'), ('LOGOUT', 'Logout'), ('UPLOAD_IMAGEM', 'Upload de Imagem de Exame'), ('ANALISE_SOLICITADA', 'Solicitação de Análise IA'), ('ANALISE_CONCLUIDA', 'Análise IA Concluída'), ('LAUDO_GERADO', 'Geração de Laudo'), ('LAUDO_IMPRESSO', 'Laudo Impresso'), ('LAUDO_ALTERADO', 'Laudo Alterado'), ('ERRO_SISTEMA', 'Erro Crítico do Sistema'), ('ACESSO_RELATORIO', 'Acesso a Relatório/Auditoria')], max_length=50)),
                ('recurso', models.CharField(blank=True, max_length=100, null=True, verbose_name='Recurso Acessado')),
                ('detalhe', models.TextField(blank=True, null=True)),
                ('ip_origem', models.CharField(max_length=45, verbose_name='IP de Origem')),
                ('protegido', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name_plural': 'Logs de Auditoria',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Sistema')),
                ('registro_profissional', models.CharField(blank=True, max_length=50, null=True, verbose_name='Registro Profissional (CRM/COREN)')),
                ('papel', models.CharField(choices=[('MEDICO', 'Médico'), ('TECNICO', 'Técnico'), ('ADMIN', 'Administrador'), ('AUDITOR', 'Auditor')], db_column='perfil', default='MEDICO', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.instituicao', verbose_name='Instituição de Afiliação')),
            ],
        ),
        migrations.AddField(
            model_name='laudo',
            name='usuario_responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.perfilusuario', verbose_name='Profissional Responsável'),
        ),
        migrations.CreateModel(
            name='HistoricoLaudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_alteracao', models.DateTimeField(auto_now_add=True)),
                ('texto_anterior', models.TextField()),
                ('ip_alteracao', models.CharField(max_length=45)),
                ('laudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.laudo')),
                ('usuario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.perfilusuario', verbose_name='Usuário da Alteração')),
            ],
        ),
    ]
