# Generated by Django 5.2.8 on 2026-01-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_paciente_possivel_diagnostico_paciente_sintomas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudo',
            name='caminho_pdf',
            field=models.FileField(blank=True, null=True, upload_to='laudos/'),
        ),
    ]
