# Generated by Django 6.0 on 2026-01-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_alter_laudo_caminho_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analiseimagem',
            name='hash_imagem',
            field=models.CharField(blank=True, max_length=100, verbose_name='Hash SHA-256 (Integridade)'),
        ),
        migrations.AlterField(
            model_name='analiseimagem',
            name='modelo_checksum',
            field=models.CharField(default='chk_sim_auto_x98y76', max_length=100, verbose_name='Checksum do Modelo'),
        ),
        migrations.AlterField(
            model_name='analiseimagem',
            name='modelo_versao',
            field=models.CharField(default='Simulador-Weka-J48-v3.5', max_length=50, verbose_name='Versão do Modelo IA'),
        ),
        migrations.AlterField(
            model_name='analiseimagem',
            name='resultado_classificacao',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando Processamento (IA)'), ('Maligno', 'Maligno'), ('Benigno', 'Benigno'), ('Cisto', 'Cisto'), ('Saudavel', 'Saudável'), ('ERRO', 'Erro no Processamento')], default='AGUARDANDO', max_length=25, verbose_name='Resultado da Classificação'),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='codigo_verificacao',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código de Verificação'),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='confirmou_concordancia',
            field=models.BooleanField(default=True, verbose_name='Confirma Concordância com IA'),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='ip_emissao',
            field=models.CharField(blank=True, max_length=45, verbose_name='IP de Emissão'),
        ),
    ]
