# Generated by Django 5.2.8 on 2026-01-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_alter_laudo_caminho_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logauditoria',
            name='acao',
            field=models.CharField(choices=[('LOGIN_SUCESSO', 'Login Bem-Sucedido'), ('LOGIN_FALHA', 'Tentativa de Login Falha'), ('LOGOUT', 'Logout'), ('PACIENTE_CRIADO', 'Paciente Criado'), ('PACIENTE_ATUALIZADO', 'Paciente Atualizado'), ('PACIENTE_EXCLUIDO', 'Paciente Excluído'), ('UPLOAD_IMAGEM', 'Upload de Imagem de Exame'), ('ANALISE_SOLICITADA', 'Solicitação de Análise IA'), ('ANALISE_CONCLUIDA', 'Análise IA Concluída'), ('LAUDO_GERADO', 'Geração de Laudo'), ('LAUDO_IMPRESSO', 'Laudo Impresso'), ('LAUDO_ALTERADO', 'Laudo Alterado'), ('ERRO_SISTEMA', 'Erro Crítico do Sistema'), ('ACESSO_RELATORIO', 'Acesso a Relatório/Auditoria')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(blank=True, help_text='Formato: dd/mm/aaaa', null=True, verbose_name='Data de Nascimento'),
        ),
    ]
