# Generated by Django 6.0 on 2026-01-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_alter_analiseimagem_hash_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analiseimagem',
            name='hash_imagem',
            field=models.CharField(default='Aguardando processamento...', max_length=100, verbose_name='Hash SHA-256 (Integridade)'),
        ),
    ]
