# Generated by Django 6.0 on 2026-01-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0006_alter_analiseimagem_hash_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudo',
            name='codigo_verificacao',
            field=models.CharField(default='Será gerado ao Salvar', max_length=50, unique=True, verbose_name='Código de Verificação'),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='ip_emissao',
            field=models.CharField(default='127.0.0.1 (Registro Interno)', max_length=45, verbose_name='IP de Emissão'),
        ),
    ]
