# Generated by Django 5.2.8 on 2025-12-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf_fake', models.CharField(max_length=14)),
                ('idade', models.IntegerField()),
                ('sintomas', models.TextField()),
                ('diagnostico_fake', models.CharField(max_length=50)),
                ('confianca', models.FloatField()),
                ('imagem_escolhida', models.FileField(upload_to='simulador_imagens/')),
                ('modo', models.CharField(default='simulado', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
