# Generated by Django 5.2.8 on 2025-12-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacao',
            name='imagem_escolhida',
            field=models.FileField(upload_to='simulador/'),
        ),
    ]
