# Generated by Django 5.2.8 on 2025-11-21 23:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instituicao', models.CharField(max_length=150, verbose_name='Nome da Instituição')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('endereco_fisico', models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço Físico')),
                ('endereco_eletronico', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email Institucional')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Instituições',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                # O Django cria um ID numérico (1, 2, 3...) automático.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # UUID é como um chassi de carro. O nome pode ser igual, o chassi nunca.
                # Isso atende a exigência de "Singularidade sem depender de autoridade central".
                ('uuid_paciente', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID Único do Paciente')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                # O sistema anota sozinho que dia a ficha foi criada (auto_now_add).
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagemExame',
            fields=[
                     # Aqui tudo fica amarrado: a imagem precisa de um Paciente existente e de um Usuário logado pra ser salva. Se tu tentar salvar uma imagem 'solta', 
                # o banco recusa. DEIXA O QUE A PROF FALOU E FOCA AQUI... A GENTE VAI BOTAR PRA FUNCIONAR!!!
                # Aqui diz quem é o dono da imagem (Paciente)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # FileField = O Django sabe lidar com upload de arquivo.
                # Ele salva o arquivo na pasta 'termografias/' e guarda só o link no banco.
                ('caminho_arquivo', models.FileField(upload_to='termografias/', verbose_name='Arquivo da Imagem')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('descricao_opcional', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_imagem', models.CharField(default='Termografia Mamária', max_length=50)),
                # Rastreabilidade! Sabemos quem fez o upload (usuário) e onde (instituição).
                ('usuario_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Upload')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.instituicao', verbose_name='Instituição')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.paciente', verbose_name='Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='AnaliseImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_hora_conclusao', models.DateTimeField(blank=True, null=True)),
                ('resultado_classificacao', models.CharField(choices=[('Maligno', 'Maligno'), ('Benigno', 'Benigno'), ('Cisto', 'Cisto'), ('Saudavel', 'Saudável')], max_length=10)),
                ('score_confianca', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('modelo_versao', models.CharField(max_length=50)),
                ('modelo_checksum', models.CharField(max_length=100)),
                ('hash_imagem', models.CharField(max_length=100)),
                ('usuario_solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Solicitante')),
                ('imagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nucleo.imagemexame', verbose_name='Imagem Analisada')),
            ],
            options={
                'verbose_name_plural': 'Análises de Imagem',
            },
        ),
        migrations.CreateModel(
            name='Laudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_emissao', models.DateTimeField(auto_now_add=True)),
                ('texto_laudo_completo', models.TextField()),
                ('caminho_pdf', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmou_concordancia', models.BooleanField(verbose_name='Confirma Concordância com IA')),
                ('ip_emissao', models.CharField(max_length=45, verbose_name='IP de Emissão')),
                ('laudo_finalizado', models.BooleanField(default=False, verbose_name='Finalizado/Bloqueado')),
                ('codigo_verificacao', models.CharField(max_length=50, unique=True)),
                ('analise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nucleo.analiseimagem', verbose_name='Análise de Origem')),
            ],
        ),
        migrations.CreateModel(
            name='LaudoImpressao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_impressao', models.DateTimeField(auto_now_add=True)),
                ('ip_origem', models.CharField(max_length=45)),
                ('local_impressao', models.CharField(blank=True, max_length=100, null=True)),
                ('laudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.laudo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('acao', models.CharField(choices=[('LOGIN_SUCESSO', 'Login Bem-Sucedido'), ('LOGIN_FALHA', 'Tentativa de Login Falha'), ('LOGOUT', 'Logout'), ('UPLOAD_IMAGEM', 'Upload de Imagem de Exame'), ('ANALISE_SOLICITADA', 'Solicitação de Análise IA'), ('ANALISE_CONCLUIDA', 'Análise IA Concluída'), ('LAUDO_GERADO', 'Geração de Laudo'), ('LAUDO_IMPRESSO', 'Laudo Impresso'), ('LAUDO_ALTERADO', 'Laudo Alterado'), ('ERRO_SISTEMA', 'Erro Crítico do Sistema'), ('ACESSO_RELATORIO', 'Acesso a Relatório/Auditoria')], max_length=50)),
                ('recurso', models.CharField(blank=True, max_length=100, null=True, verbose_name='Recurso Acessado')),
                ('detalhe', models.TextField(blank=True, null=True)),
                ('ip_origem', models.CharField(max_length=45, verbose_name='IP de Origem')),
                ('protegido', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name_plural': 'Logs de Auditoria',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                # OneToOneField = "Um pra Um". Significa que cada login (User) só tem UM crachá.
                # Ninguém pode ser Médico e Faxineiro ao mesmo tempo nesse sistema. ;)
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Sistema')),
                ('registro_profissional', models.CharField(blank=True, max_length=50, null=True, verbose_name='Registro Profissional (CRM/COREN)')),
                # Aqui são os "Papéis" (Roles) do RBAC.
                # O banco grava 'MEDICO', 'ADMIN', etc. É aqui que vai validar se a pessoa pode entrar.
                ('perfil', models.CharField(choices=[('MEDICO', 'Médico'), ('TECNICO', 'Técnico'), ('ADMIN', 'Administrador'), ('AUDITOR', 'Auditor')], default='MEDICO', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                #ForeignKey = "Chave Estrangeira".
                # Significa que esse usuário PERTENCE a uma Instituição.
                # O 'on_delete=PROTECT' é um cão de guarda: Se tentarem apagar a Instituição,
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.instituicao', verbose_name='Instituição de Afiliação')),
            ],
        ),
        migrations.AddField(
            model_name='laudo',
            name='usuario_responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.perfilusuario', verbose_name='Profissional Responsável (Validação)'),
        ),
        migrations.CreateModel(
            name='HistoricoLaudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_alteracao', models.DateTimeField(auto_now_add=True)),
                ('texto_anterior', models.TextField()),
                ('ip_alteracao', models.CharField(max_length=45)),
                ('laudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.laudo')),
                ('usuario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.perfilusuario', verbose_name='Usuário da Alteração')),
            ],
        ),
    ]
