# Generated by Django 5.2.8 on 2025-12-02 02:30

import django.db.models.deletion
import nucleo.seguranca.encrypted_char_field
import nucleo.seguranca.encrypted_file_field
import nucleo.seguranca.encrypted_storage
import nucleo.seguranca.encrypted_text_field
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instituicao', models.CharField(max_length=150, verbose_name='Nome da Instituição')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('endereco_fisico', models.CharField(blank=True, max_length=200, null=True)),
                ('endereco_eletronico', models.EmailField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Instituições',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_paciente', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cpf', nucleo.seguranca.encrypted_char_field.EncryptedCharField(blank=True, max_length=14, null=True, unique=True)),
                ('nome_completo', nucleo.seguranca.encrypted_char_field.EncryptedCharField(max_length=150)),
                ('data_nascimento', nucleo.seguranca.encrypted_char_field.EncryptedCharField(blank=True, max_length=20, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Simulacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf_fake', models.CharField(max_length=14)),
                ('idade', models.IntegerField()),
                ('sintomas', models.TextField()),
                ('diagnostico_fake', models.CharField(max_length=50)),
                ('confianca', models.FloatField()),
                ('imagem_escolhida', models.FileField(upload_to='simulador/')),
                ('modo', models.CharField(default='simulado', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagemExame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caminho_arquivo', nucleo.seguranca.encrypted_file_field.EncryptedFileField(storage=nucleo.seguranca.encrypted_storage.EncryptedStorage(), upload_to='termografias/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('descricao_opcional', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_imagem', models.CharField(default='Termografia Mamária', max_length=50)),
                ('usuario_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.instituicao')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='AnaliseImagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_hora_conclusao', models.DateTimeField(blank=True, null=True)),
                ('resultado_classificacao', models.CharField(choices=[('Maligno', 'Maligno'), ('Benigno', 'Benigno'), ('Cisto', 'Cisto'), ('Saudavel', 'Saudável')], max_length=10)),
                ('score_confianca', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('modelo_versao', models.CharField(max_length=50)),
                ('modelo_checksum', models.CharField(max_length=100)),
                ('hash_imagem', models.CharField(max_length=100)),
                ('usuario_solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('imagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nucleo.imagemexame')),
            ],
            options={
                'verbose_name_plural': 'Análises de Imagem',
            },
        ),
        migrations.CreateModel(
            name='Laudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_emissao', models.DateTimeField(auto_now_add=True)),
                ('texto_laudo_completo', nucleo.seguranca.encrypted_text_field.EncryptedTextField()),
                ('caminho_pdf', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmou_concordancia', models.BooleanField()),
                ('ip_emissao', models.CharField(max_length=45)),
                ('laudo_finalizado', models.BooleanField(default=False)),
                ('codigo_verificacao', models.CharField(max_length=50, unique=True)),
                ('analise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nucleo.analiseimagem')),
            ],
        ),
        migrations.CreateModel(
            name='LaudoImpressao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_impressao', models.DateTimeField(auto_now_add=True)),
                ('ip_origem', models.CharField(max_length=45)),
                ('local_impressao', models.CharField(blank=True, max_length=100, null=True)),
                ('laudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.laudo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('acao', models.CharField(choices=[('LOGIN_SUCESSO', 'Login Bem-Sucedido'), ('LOGIN_FALHA', 'Tentativa de Login Falha'), ('LOGOUT', 'Logout'), ('UPLOAD_IMAGEM', 'Upload de Imagem de Exame'), ('ANALISE_SOLICITADA', 'Solicitação de Análise IA'), ('ANALISE_CONCLUIDA', 'Análise IA Concluída'), ('LAUDO_GERADO', 'Geração de Laudo'), ('LAUDO_IMPRESSO', 'Laudo Impresso'), ('LAUDO_ALTERADO', 'Laudo Alterado'), ('ERRO_SISTEMA', 'Erro Crítico do Sistema'), ('ACESSO_RELATORIO', 'Acesso a Relatório/Auditoria')], max_length=50)),
                ('recurso', models.CharField(blank=True, max_length=100, null=True)),
                ('detalhe', nucleo.seguranca.encrypted_text_field.EncryptedTextField(blank=True, null=True)),
                ('ip_origem', models.CharField(max_length=45)),
                ('protegido', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Logs de Auditoria',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('registro_profissional', models.CharField(blank=True, max_length=50, null=True)),
                ('papel', models.CharField(choices=[('MEDICO', 'Médico'), ('TECNICO', 'Técnico'), ('ADMIN', 'Administrador'), ('AUDITOR', 'Auditor')], default='MEDICO', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.instituicao')),
            ],
        ),
        migrations.AddField(
            model_name='laudo',
            name='usuario_responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.perfilusuario'),
        ),
        migrations.CreateModel(
            name='HistoricoLaudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_alteracao', models.DateTimeField(auto_now_add=True)),
                ('texto_anterior', nucleo.seguranca.encrypted_text_field.EncryptedTextField()),
                ('ip_alteracao', models.CharField(max_length=45)),
                ('laudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.laudo')),
                ('usuario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.perfilusuario')),
            ],
        ),
    ]
