# Generated by Django 5.2.8 on 2025-12-03 02:28

import django.db.models.deletion
import nucleo.seguranca.encrypted_char_field
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_remove_paciente_possivel_diagnostico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='possivel_diagnostico',
            field=nucleo.seguranca.encrypted_char_field.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sintomas',
            field=nucleo.seguranca.encrypted_char_field.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analiseimagem',
            name='imagem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nucleo.imagemexame', verbose_name='Imagem Analisada'),
        ),
        migrations.AlterField(
            model_name='analiseimagem',
            name='usuario_solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Solicitante'),
        ),
        migrations.AlterField(
            model_name='historicolaudo',
            name='texto_anterior',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historicolaudo',
            name='usuario_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.perfilusuario', verbose_name='Usuário da Alteração'),
        ),
        migrations.AlterField(
            model_name='imagemexame',
            name='caminho_arquivo',
            field=models.FileField(upload_to='imagens_reais/', verbose_name='Arquivo da Imagem Real'),
        ),
        migrations.AlterField(
            model_name='imagemexame',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.instituicao', verbose_name='Instituição'),
        ),
        migrations.AlterField(
            model_name='imagemexame',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='imagemexame',
            name='tipo_imagem',
            field=models.CharField(default='Exame Real', max_length=50),
        ),
        migrations.AlterField(
            model_name='imagemexame',
            name='usuario_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que fez o upload'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='endereco_eletronico',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email Institucional'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='endereco_fisico',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço Físico'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logotipo da Clínica'),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='analise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nucleo.analiseimagem', verbose_name='Análise de Origem'),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='confirmou_concordancia',
            field=models.BooleanField(verbose_name='Confirma Concordância com IA'),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='ip_emissao',
            field=models.CharField(max_length=45, verbose_name='IP de Emissão'),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='laudo_finalizado',
            field=models.BooleanField(default=False, verbose_name='Finalizado/Bloqueado'),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='texto_laudo_completo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='usuario_responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.perfilusuario', verbose_name='Profissional Responsável'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='detalhe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='ip_origem',
            field=models.CharField(max_length=45, verbose_name='IP de Origem'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='recurso',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Recurso Acessado'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=nucleo.seguranca.encrypted_char_field.EncryptedCharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=nucleo.seguranca.encrypted_char_field.EncryptedCharField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_completo',
            field=nucleo.seguranca.encrypted_char_field.EncryptedCharField(max_length=150, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='uuid_paciente',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID Único do Paciente'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.instituicao', verbose_name='Instituição de Afiliação'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='papel',
            field=models.CharField(choices=[('MEDICO', 'Médico'), ('TECNICO', 'Técnico'), ('ADMIN', 'Administrador'), ('AUDITOR', 'Auditor')], db_column='perfil', default='MEDICO', max_length=10),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='registro_profissional',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Registro Profissional (CRM/COREN)'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Sistema'),
        ),
    ]
