# Generated by Django 5.2.8 on 2025-11-26 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_create_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='perfil',
            field=models.CharField(choices=[('MEDICO', 'Médico'), ('TECNICO', 'Técnico'), ('ADMIN', 'Administrador'), ('AUDITOR', 'Auditor')], db_column='perfil', default='MEDICO', max_length=10),
        ),
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='perfil',
            new_name='papel',
        ),
        migrations.AddField(
            model_name='instituicao',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logotipo da Clínica'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='usuario_responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.perfilusuario', verbose_name='Profissional Responsável'),
        ),
    ]
