# Generated by Django 5.2.8 on 2025-11-27 22:43
from django.db import migrations
from nucleo.seguranca import (
    EncryptedTextField,
    EncryptedCharField
)


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_alter_perfilusuario_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicolaudo',
            name='texto_anterior',
            field=EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='texto_laudo_completo',
            field=EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='detalhe',
            field=EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=EncryptedCharField(
                blank=True,
                max_length=14,
                null=True,
                unique=True,
                verbose_name='CPF'
            ),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=EncryptedCharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name='Data de Nascimento'
            ),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_completo',
            field=EncryptedCharField(
                max_length=150,
                verbose_name='Nome Completo'
            ),
        ),
    ]
