# Generated by Django 5.2.8 on 2025-11-29 19:12

import django.db.models.deletion
import nucleo.seguranca.encrypted_char_field
import nucleo.seguranca.encrypted_file_field
import nucleo.seguranca.encrypted_storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_alter_historicolaudo_texto_anterior_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='analiseimagem',
            name='imagem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nucleo.imagemexame'),
        ),
        migrations.AlterField(
            model_name='analiseimagem',
            name='usuario_solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicolaudo',
            name='usuario_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.perfilusuario'),
        ),
        migrations.AlterField(
            model_name='imagemexame',
            name='caminho_arquivo',
            field=nucleo.seguranca.encrypted_file_field.EncryptedFileField(storage=nucleo.seguranca.encrypted_storage.EncryptedStorage(), upload_to='termografias/'),
        ),
        migrations.AlterField(
            model_name='imagemexame',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.instituicao'),
        ),
        migrations.AlterField(
            model_name='imagemexame',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.paciente'),
        ),
        migrations.AlterField(
            model_name='imagemexame',
            name='usuario_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='endereco_eletronico',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='endereco_fisico',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='analise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nucleo.analiseimagem'),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='confirmou_concordancia',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='ip_emissao',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='laudo_finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='usuario_responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.perfilusuario'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='ip_origem',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='recurso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=nucleo.seguranca.encrypted_char_field.EncryptedCharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=nucleo.seguranca.encrypted_char_field.EncryptedCharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_completo',
            field=nucleo.seguranca.encrypted_char_field.EncryptedCharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='uuid_paciente',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.instituicao'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='papel',
            field=models.CharField(choices=[('MEDICO', 'Médico'), ('TECNICO', 'Técnico'), ('ADMIN', 'Administrador'), ('AUDITOR', 'Auditor')], default='MEDICO', max_length=10),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='registro_profissional',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
